[colors]
ansi = [
  '#fbf1f2',
  '#d57e85',
  '#a3b367',
  '#dcb16c',
  '#7297b9',
  '#bb99b4',
  '#69a9a7',
  '#8b8198',
]
background = '#fbf1f2'
brights = [
  '#bfb9c6',
  '#d57e85',
  '#a3b367',
  '#dcb16c',
  '#7297b9',
  '#bb99b4',
  '#69a9a7',
  '#585062',
]
cursor_bg = '#8b8198'
cursor_border = '#8b8198'
cursor_fg = '#8b8198'
foreground = '#8b8198'
selection_bg = '#8b8198'
selection_fg = '#fbf1f2'

[colors.indexed]

[metadata]
author = 'DavFeng1 (github.com/DavFeng1)'
name = 'Quiet Light'
